version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - ipv6_network
      - ipv4_network


  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=run.py
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - ipv6_network
      - ipv4_network


  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    networks:
      - ipv6_network
      - ipv4_network

networks:
  ipv6_network:
    enable_ipv6: true
    driver: bridge
  ipv4_network:
    driver: bridge


